---
apiVersion: app.terraform.io/v1alpha2
kind: AgentPool
metadata:
  name: my-agent-pool
spec:
  organization: hashi-demos-apj
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  name: agent-pool-development
  agentTokens:
    - name: token-red
