server:
  extraSecretEnvironmentVars:
    - envName: AWS_ACCESS_KEY_ID
      secretName: vault-secrets
      secretKey: AWS_ACCESS_KEY_ID
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: vault-secrets
      secretKey: AWS_SECRET_ACCESS_KEY
    - envName: AWS_SESSION_TOKEN
      secretName: vault-secrets
      secretKey: AWS_SESSION_TOKEN
  enterpriseLicense:
    secretName: "vault-secrets"
    secretKey: "license"
  image:
    repository: "hashicorp/vault-enterprise"
    tag: "1.13.0-rc1-ent"
    # Overrides the default Image Pull Policy
    pullPolicy: IfNotPresent
  affinity: ""
  ha:
    enabled: true
    raft:
      enabled: true
  ingress:
    enabled: true
    activeService: true
    hosts:
      - host: localhost
ui:
  enabled: true
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 32001
