server:
  extraSecretEnvironmentVars:
    - envName: AWS_ACCESS_KEY_ID
      secretName: vault-secrets
      secretKey: AWS_ACCESS_KEY_ID
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: vault-secrets
      secretKey: AWS_SECRET_ACCESS_KEY
    - envName: AWS_SESSION_TOKEN
      secretName: vault-secrets
      secretKey: AWS_SESSION_TOKEN
  enterpriseLicense:
    secretName: "vault-secrets"
    secretKey: "license"
  image:
    repository: "hashicorp/vault-enterprise"
    tag: "latest"
    # Overrides the default Image Pull Policy
    pullPolicy: IfNotPresent
  affinity: ""
  ha:
    enabled: true
  ingress:
    labels:
      traffic: external
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    pathType: Prefix
    activeService: false
    hosts:
      - host: vault.hashibank.com
        paths: []
    tls:
      - secretName: vault-secrets
        hosts:
          - vault.hashibank.com