global:
  enabled: true
  tlsDisable: true
server:
  enabled: "-"
  enterpriseLicense:
    secretName: "vault-secrets"
    secretKey: "license"
  image:
    repository: "hashicorp/vault-enterprise"
    tag: "latest"
    # Overrides the default Image Pull Policy
    pullPolicy: IfNotPresent
  extraSecretEnvironmentVars:
    - envName: AWS_ACCESS_KEY_ID
      secretName: vault-secrets
      secretKey: AWS_ACCESS_KEY_ID
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: vault-secrets
      secretKey: AWS_SECRET_ACCESS_KEY
    - envName: AWS_SESSION_TOKEN
      secretName: vault-secrets
      secretKey: AWS_SESSION_TOKEN
  affinity: ""
  ha:
    enabled: true
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          # Enable unauthenticated metrics access (necessary for Prometheus Operator)
          #telemetry {
          #  unauthenticated_metrics_access = "true"
          #}
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}
  ingress:
    labels:
      traffic: external
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    pathType: Prefix
    activeService: false
    hosts:
      - host: vault.hashibank.com
        paths: []
    tls:
      - secretName: vault-secrets
        hosts:
          - vault.hashibank.com