apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: my-vault-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-data
        emptyDir: {}
      - name: ca-cert
        configMap:
          name: kubernetes-ca
      initContainers:
      - name: init-prometheus
        image: busybox
        command: ['/bin/sh', '-c', 'echo -n "$VAULT_TOKEN" > /etc/prometheus/prometheus-token']
        env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: prometheus-token
              key: prometheus-token
        volumeMounts:
        - name: prometheus-data
          mountPath: /etc/prometheus
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-data
          mountPath: /etc/prometheus
        - name: ca-cert
          mountPath: /etc/prometheus/ca.crt
          subPath: ca.crt
      restartPolicy: Always
