apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: my-vault-demo
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: web
  selector:
    app: prometheus
