apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: my-vault-demo
spec:
  ingressClassName: nginx
  rules:
    - host: demo.example.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: demo
                port:
                  number: 8080
            path: /
  tls:
  - hosts:
    - demo.example.com
    secretName: demo-example-com-tls