apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer-v2
  namespace: my-vault-demo
spec:
  vault:
    server: https://vault-dc1-active.my-vault-demo.svc.cluster.local:8200
    path: demo-pki-intermediate/sign/my_role
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRkdvRTBEMGIzNmt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMk1ETXhNREl6TVRKYUZ3MHpOREEyTURFeE1ESTRNVEphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMzZnkybFRrUGlQZVRPZm9YRTlKQVprcTNWcWJnQWxUVzEwWExtSWxqZURlY2E1SEEyYXhvcnlxM1MKOVo4YUM2MlV2ek1MVi9tU21rd1hWRkdHbmxlcUQvanBkeGVOOXFVN2VTZ3FJeXBnbXVVT3QxQXd3djZpUi9NTQpNcDdlOXp0cDUxYWpUbUN1bUM2d1RBQWtRRExCTE85NFo3d2ZGbENmcy9oeHU3clBEVS8zVkI3VDdNZHlQdm0yCmFrcXk1djBHYXN6alB1RnVxUnlpRlZNb2FQYlluVkFTczlzUVhwRlJPOHhvQlhtejZKS3QyVjlaL0hjTUt6SVYKbWh4UlV2amRkQ3REWjlHRUczczRldTVUT29QaEJ6cGYxZUxJa0xVNHZ2VHZSK2E1enJsRGo0VTlHTjRJSTVlLwpFSTFWcG95dWJYMm5yTE4wR0JoQWVTaHF4bzFoQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRV1JaR09pKzNhMzVjRXprMjk4MlU4cWV1SEJ6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkhqdms0dzR6dQpnMjFRbDE5aEtCTlkwU1dKTDFLQXV0UUFlazk1QjdtR2JCV2JyWDJUbUM4QUwrRFhoWERXSVZNTlprdStOVDl2CngxWWVFV01DbnNzZyt6WVBYeHhIK0dDUXZiT0JUQlpZbnBxbE1ISWlLU0RjMGp2dzN4MUt1SStJSkFaM0pNeU0KOVcyVzRNUTZ2WGEwQytrV0dmcTEyNE8wRU5DdUpsWUdJTzA4eTJiM3FzbUpMT2E1QUVTaFhMM0ViVlBSY1ZWdAp0QndmVGFkem1Wck5QUWlTOTRiTlIwcWVPemFvZjM0ci9oYlplUkJPdWxQVFpod0M1ZGtUVTI2bFBwQWRxV3p6Cm5VdDJvdXY3b3M0UDkzWXFJV09lVjVkN0FiQURDa1RSMURpbUFzY0d3c3NNY2R1bHF0Nmh1dEdUUE9ZVUV0R2UKZ3Vwb29tb2xYZ0h0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"  # Placeholder to be replaced
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: webapp
        secretRef:
          name: issuer-token-v2
          key: token
