apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: my-vault-demo
spec:
  vault:
    server: http://vault-dc1-active:8200
    path: demo-pki/sign/my_role
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: webapp
        secretRef:
          name: issuer-token-lmzpj
          key: token