# caddy-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: caddy-service
  namespace: my-vault-demo
spec:
  selector:
    app: caddy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: ClusterIP
