apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: my-vault-demo
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: web
  selector:
    app: grafana
