name: GitHub Actions with Vault

on:
  workflow_dispatch:
  push:

jobs:
  process_secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
        name: Check out repository code

      - name: Authenticate to Vault and Import Secrets
        id: vault_auth
        uses: hashicorp/vault-action@v2.7.2
        with:
          url: ${{ secrets.VAULT_URL }}
          role: 'github-test-role'
          method: jwt
          jwtGithubAudience: 'https://github.com/hashi-demo-lab'
          tlsSkipVerify: true
          outputToken: true
          secrets: demo-key-value/data/aarons-secrets role | ROLE
      - run: echo "my secret role hash is':' $(echo -n "${{ steps.import-secrets.outputs.ROLE }}" | sha256sum)"
      - run: echo "my secret role is':' ${{ steps.import-secrets.outputs.ROLE }} " | sed 's/ //g'

      - name: Run Encrypt Script
        run: |
          echo "Running encryption script..."
          python encrypt.py
        env:
          VAULT_URL: ${{ secrets.VAULT_URL }}
          VAULT_TOKEN: ${{ steps.vault_auth.outputs.vault_token }}
          KEY_NAME: ${{ secrets.KEY_NAME }}

      - name: Display Outcome
        run: echo "Encryption and Decryption processes completed."
