name: GitHub Actions with Vault

on:
  workflow_dispatch:
  push:

jobs:
  process_secrets:
    runs-on: arc-runner-set
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
        name: Check out repository code

      - name: Authenticate to Vault and Import Secrets
        id: vault_auth
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          role: 'github-test-role'
          method: jwt
          jwtGithubAudience: 'https://github.com/hashi-demo-lab'
          tlsSkipVerify: true
          outputToken: true
          exportEnv: true
          secrets: 'demo-key-value/data/aarons-secrets role | ROLE'
          
      - run: echo "my secret role hash is':' $(echo -n "${{ steps.vault_auth.outputs.ROLE }}" | sha256sum)"
      - run: echo "my secret role is':' ${{ steps.vault_auth.outputs.ROLE }} " | sed 's/ //g'
 

      - name: Run Encrypt Script
        run: |
          echo "Running encryption script..."
          python3 vault-eaas/encrypt.py
        env:
          vault_addr: ${{ secrets.VAULT_ADDR }}
          vault_token: ${{ steps.vault_auth.outputs.vault_token }}
          key_name: ${{ secrets.KEY_NAME }}
          s3_bucket_name: ${{ secrets.S3_BUCKET_NAME }}
          s3_file_key: ${{ secrets.S3_FILE_KEY }}
          local_file_name: ${{ secrets.LOCAL_FILE_NAME }}

      - name: Display Outcome
        run: echo "Encryption and Decryption processes completed."